### ISSUE TITLE
Checkbox appears to the right of the label

### ISSUE THREAD

**Issue by jattwood** [marceldigital/Umbraco-Forms-Bootstrap-4-Theme#14]
Great package and much needed! Thank you. I am using checkboxes and the labels are appearing to the left of the checkboxes rather than the expected right placement. I see that there is a label injected to the right that contains a non breakable space. However, the default label is the one that contains the text:

![image](https://user-images.githubusercontent.com/6452616/80492383-ecf36b80-8931-11ea-8ecc-c7d63b503366.png)

**Comment by vipervf1** [comment]
Hi @jattwood!

I assume you are talking about the Horizontal Theme?

A workaround for this would be to edit the following templates:
/Views/Partials/Forms/Themes/Horizontal/Form.cshtml
Line 48:
``` csharp
@if (!f.HideLabel && f.FieldTypeName != "Checkbox")
```
Line 59:
``` html
<div class="umbraco-forms-field-wrapper col-sm-10 @(f.FieldTypeName == "Checkbox" ? "offset-sm-2" : null)">
```

And then replacing 
/Views/Partials/Forms/Themes/Horizontal/FieldTypes/FieldType.CheckBox.cshtml
with this:
``` csharp
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@using Umbraco.Forms.Mvc

<div class="custom-control custom-checkbox">
    <input type="checkbox" name="@Model.Name" id="@Model.Id"
           class="custom-control-input @Html.ValidationClass(Model.Id)"
           @if (Model.Mandatory) { <text> data-val="true" data-val-requiredcb="@Model.RequiredErrorMessage" </text> }
           @if (Model.ContainsValue(true) || Model.ContainsValue("true") || Model.ContainsValue("on")) { <text> checked="checked" </text> } />
    <label class="custom-control-label" for="@Model.Name">@Model.Caption</label>
</div>
```

That looks like this:
![image](https://user-images.githubusercontent.com/8094628/80499489-a94d3180-8932-11ea-8dcb-7e06a53f34f7.png)

**Comment by jattwood** [comment]
Yes, the Horizontal theme. This is a great fix - Thank you!

**Comment by jattwood** [comment]
Just a quick note that I needed to add a reference to your Extensions in order to override /Views/Partials/Forms/Themes/Horizontal/FieldTypes/FieldType.CheckBox.cshtml

```
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@using Umbraco.Forms.Mvc
@using MarcelDigital.Umbraco.Bootstrap4FormsTheme.Extensions

<div class="custom-control custom-checkbox">
    <input type="checkbox" name="@Model.Name" id="@Model.Id"
           class="custom-control-input @Html.ValidationClass(Model.Id)"
           @if (Model.Mandatory) { <text> data-val="true" data-val-requiredcb="@Model.RequiredErrorMessage" </text> }
           @if (Model.ContainsValue(true) || Model.ContainsValue("true") || Model.ContainsValue("on")) { <text> checked="checked" </text> } />
    <label class="custom-control-label" for="@Model.Name">@Model.Caption</label>
</div>
```

**Comment by vipervf1** [comment]
Awesome! If you have it working and want to share, please create a pull request.

**Comment by jattwood** [comment]
Sure - what versions should I compare against?

**Comment by vipervf1** [comment]
I think the lowest we support is Umbraco Forms v6.0.0

So if you want to check that and the latest v7.4.1 should be enough.

**Comment by jattwood** [comment]
Ok trying to push my branch but you might need to give me write access so I can create a pull request.

Thanks!

**Comment by vipervf1** [comment]
I think you might need to fork the repository, make the changes, and then merge the fork in.

**Comment by jattwood** [comment]
Ok I’ll give it a shot.

Jamie Attwood

Protean Interactive
416-895-2932
________________________________
