### ISSUE TITLE
Location of umbracoforms.js files has changed in umbraco forms

### ISSUE THREAD

**Issue by RobbieHoven** [marceldigital/Umbraco-Forms-Bootstrap-4-Theme#9]
Hi,

In the latest versions of Umbraco Forms (at least v7.0.6), the client JS files are in the root Assets folder instead of Assets/Themes/Default. So I needed to modify App_Plugins/UmbracoFormsBootstrap4/Views/Script.cshtml

 Html.AddFormThemeScriptFile(Model,
/App_Plugins/UmbracoForms/Assets/**Themes/Default**/umbracoforms-dependencies.js);
    Html.AddFormThemeScriptFile(Model, ~/App_Plugins/UmbracoForms/Assets/**Themes/Default**/umbracoforms.js);
    Html.AddFormThemeScriptFile(Model, ~/App_Plugins/UmbracoForms/Assets/**Themes/Default**/umbracoforms-conditions.js);

**Comment by vipervf1** [comment]
@RobbieHoven Thanks for finding this!

Looks like these files were removed in 7.0.6

I'm going to see if there is a generic fix to work across versions.

**Comment by vipervf1** [comment]
@RobbieHoven Should be fixed in v1.0.1!

Please reopen if it's still not working.
